name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build 
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} 
          -DCMAKE_CXX_STANDARD=17

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Print Error Details
        if: failure()
        run: cat ${{github.workspace}}/build/CMakeFiles/CMakeError.log || true