name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build 
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} 
          -DBUILD_TESTS=ON 
          -DCMAKE_CXX_STANDARD=14

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure

      - name: Print Error Details
        if: failure()
        run: cat ${{github.workspace}}/build/CMakeFiles/CMakeError.log || true